---
# tasks file for webserver
- name: "installing required package"
  package:
          name: "httpd"
          state: present

- name: "Copying content to the webserver"
  copy:
          content: "Hey there!! The website has been deployed on {{ ansible_hostname  }}"
          dest: "/var/www/html/index.html"

- name: "Starting the webservice"
  service:
          name: "httpd"
          state: started
          enabled: yes

         
